#include <stdio.h>
#include <unistd.h>


#include "list.h"

int main() {
    DLList* lst = DLListAlloc();
    //sleep(1);
    DLLIST_INIT(lst, 10);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListInsertL(lst, DLListGetHead(lst), 11);
    DLListInsertL(lst, DLListGetHead(lst), 40);
    DLListInsertL(lst, DLListGetHead(lst), 100);
    DLListInsertL(lst, DLListGetHead(lst), 45);
    DLListInsertL(lst, DLListGetHead(lst), 20);
    DLListInsertR(lst, DLListGetTail(lst), 10);
    DLListInsertR(lst, DLListGetTail(lst), 13);
    DLListInsertR(lst, DLListGetTail(lst), 12);
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListDelete(lst, DLListGetTail(lst));
    DLListDelete(lst, DLListGetHead(lst));
    DLListSort(lst);
    DLListFree(lst);

    return 0;
}